import { GovernmentScheme, DocumentItem, ActionPlanTask, EntrepreneurProfile, BusinessProject } from '../types';

export const HERO_IMAGE = '/src/assets/images/hero_entrepreneur_women_1791486986434.jpg';
export const CATEGORY_FOOD_IMAGE = '/src/assets/images/category_food_snack_1791486998212.jpg';
export const CATEGORY_TAILORING_IMAGE = '/src/assets/images/category_tailoring_craft_1791487012045.jpg';

export interface SectorMeta {
  id: string;
  title: Record<string, string>;
  desc: Record<string, string>;
  minBudget: number;
  icon: string;
  image?: string;
}

export const BUSINESS_SECTORS_META: SectorMeta[] = [
  {
    id: 'food_snacks',
    title: { en: 'Tea, Snacks & Food Stall', hi: 'चाय, नाश्ता एवं खाद्य स्टॉल', mr: 'चहा, नाश्ता आणि अन्न व्यवसाय' },
    desc: { en: 'Poha, vadapav, tea stalls, homemade snacks', hi: 'पोहा, वड़ापाव, चाय की दुकान, घरेलू नाश्ता', mr: 'पोहे, वडापाव, चहा टपरी, घरगुती स्नॅक्स' },
    minBudget: 15000,
    icon: 'Utensils',
    image: CATEGORY_FOOD_IMAGE,
  },
  {
    id: 'tailoring_clothing',
    title: { en: 'Tailoring & Boutique', hi: 'सिलाई, कढ़ाई एवं बुटीक', mr: 'शिलाई, भरतकाम आणि कपडे' },
    desc: { en: 'Blouse alteration, custom stitching, dressmaking', hi: 'ब्लाउज सिलाई, कपड़े सिलना, बुटीक कार्य', mr: 'ब्लाऊज शिलाई, कपडे शिवणे, बुटीक' },
    minBudget: 20000,
    icon: 'Scissors',
    image: CATEGORY_TAILORING_IMAGE,
  },
  {
    id: 'beauty_wellness',
    title: { en: 'Beauty & Personal Care', hi: 'ब्यूटी पार्लर व सौंदर्य सेवाएं', mr: 'ब्युटी पार्लर आणि सौंदर्य सेवा' },
    desc: { en: 'Home salon, mehndi application, skincare', hi: 'होम पार्लर, मेहंदी, सौंदर्य सेवा', mr: 'होम पार्लर, मेहंदी, सौंदर्य सेवा' },
    minBudget: 25000,
    icon: 'Sparkles',
  },
  {
    id: 'agriculture_farming',
    title: { en: 'Agri-Products & Dairy', hi: 'कृषि उत्पाद व डेयरी', mr: 'शेती उत्पादने आणि दुग्धव्यवसाय' },
    desc: { en: 'Goat farming, milk collection, organic vegetables', hi: 'बकरी पालन, दूध उत्पादन, सब्जी विक्रय', mr: 'शेळीपालन, दुग्धव्यवसाय, भाजीपाला' },
    minBudget: 30000,
    icon: 'Sprout',
  },
  {
    id: 'handmade_crafts',
    title: { en: 'Handmade Crafts & Gifts', hi: 'हस्तशिल्प व हस्तकला उत्पाद', mr: 'हस्तकला आणि गृहउद्योग' },
    desc: { en: 'Incense sticks, paper bags, festive decor', hi: 'अगरबत्ती, कागज के थैले, त्योहार सजावट', mr: 'अगरबत्ती, कागदी पिशव्या, हस्तकला' },
    minBudget: 10000,
    icon: 'Palette',
  },
  {
    id: 'retail_shop',
    title: { en: 'Retail & Corner Shop', hi: 'किराना व स्थानीय दुकान', mr: 'किराणा व जनरल स्टोअर' },
    desc: { en: 'Spices, grains, stationery, daily essentials', hi: 'मसाले, राशन, दैनिक जरूरी सामान', mr: 'मसाले, किराणा माल, स्टेशनरी' },
    minBudget: 35000,
    icon: 'Store',
  },
] as const;

export const INITIAL_DEMO_PROFILE: EntrepreneurProfile = {
  id: 'usr_sunita_pawar_01',
  fullName: 'Sunita Anand Pawar',
  preferredName: 'Sunita Tai',
  ageBand: '26-35',
  state: 'Maharashtra',
  district: 'Pune',
  villageTown: 'Shirur',
  language: 'mr',
  interactionMode: 'both',
  educationLevel: 'secondary',
  existingOccupation: 'Homemaker and seasonal farm helper',
  previousBusinessExperience: false,
  businessSector: 'food_snacks',
  businessStage: 'planning',
  availableInvestment: 30000,
  monthlyIncomeBand: '₹10,000 - ₹20,000',
  monthlyInvestableAmount: 5000,
  hasSmartphone: true,
  hasInternet: true,
  hasWorkspace: false,
  accessibilityPreferences: ['large_text', 'audio_readout'],
  role: 'entrepreneur',
  createdAt: '2026-03-15T09:00:00Z',
};

export const INITIAL_DEMO_PROJECT: BusinessProject = {
  id: 'prj_sai_shakti_snacks_01',
  userId: 'usr_sunita_pawar_01',
  title: 'Sai Shakti Snacks & Tea Centre',
  sector: 'food_snacks',
  ideaDescription: 'Clean morning breakfast and evening tea stall serving poha, vadapav, and spiced masala tea near the Shirur bus terminus market area.',
  budgetInINR: 30000,
  targetDailyCustomers: 80,
  operationMode: 'stall',
  stage: 'planning',
  location: 'Shirur Market Road, Pune Rural',
  hasEquipment: false,
  equipmentNotes: 'Need 1 commercial burner, gas cylinder, tea kettle, stainless steel utensils, and clean snack containers.',
  planCompletionPercentage: 42,
  createdAt: '2026-03-15T09:30:00Z',
  updatedAt: '2026-03-20T11:15:00Z',
};

export const VERIFIED_GOVERNMENT_SCHEMES: GovernmentScheme[] = [
  {
    id: 'sch_mudra_shishu',
    officialName: 'Pradhan Mantri MUDRA Yojana (PMMY) - Shishu Category',
    popularName: 'Mudra Shishu Loan (₹50,000 Collateral-Free)',
    schemeType: 'loan',
    implementingAuthority: 'Ministry of Finance & MUDRA Ltd, Govt. of India',
    description: 'Provides collateral-free loans up to ₹50,000 for micro-enterprises, small shopkeepers, and street vendors to purchase tools, raw materials, and initial working capital.',
    targetBeneficiaries: ['Women micro-entrepreneurs', 'Small food stalls', 'Street vendors', 'Artisans'],
    eligibleSectors: ['food_snacks', 'tailoring_clothing', 'beauty_wellness', 'retail_shop', 'handmade_crafts'],
    geographicScope: 'Pan India (Urban, Semi-Urban, and Rural branches of commercial and RRB banks)',
    maxFundingAmountINR: 50000,
    interestRateAnnualPercent: 8.5,
    collateralRequired: false,
    applicationUrl: 'https://www.udyamimitra.in',
    officialSourceUrl: 'https://www.mudra.org.in',
    lastVerifiedDate: '2026-02-10',
    recordStatus: 'active',
    sourceExcerpt: 'Shishu category covers loans up to ₹50,000. No collateral or third-party guarantee is required. Processing fee is nil for Shishu category.',
    whyRecommended: 'Matches your food stall idea and investment needs (₹30,000). The Shishu tier requires zero collateral and provides up to ₹50,000 working capital with simple documentation.',
    overallStatus: 'eligible',
    requiredDocuments: ['Aadhaar Card', 'PAN Card or Form 60', 'Bank Passbook (6 months)', 'Quotation for equipment/utensils', '2 Passport Photos'],
    criteria: [
      {
        id: 'crit_1',
        label: 'Indian Citizen aged 18 years or above',
        status: 'pass',
        explanation: 'Profile indicates age is in the 26-35 bracket and location is Maharashtra, India.',
        userValue: 'Age 26-35, Maharashtra',
        requiredRule: 'Minimum 18 years, Citizen of India',
      },
      {
        id: 'crit_2',
        label: 'Micro/Small Non-Farm Commercial Activity',
        status: 'pass',
        explanation: 'Food and tea stall is an eligible micro commercial activity under PMMY guidelines.',
        userValue: 'Food & Snacks Stall',
        requiredRule: 'Manufacturing, trading, or service micro-enterprise',
      },
      {
        id: 'crit_3',
        label: 'Loan requirement up to ₹50,000',
        status: 'pass',
        explanation: 'Your planned budget is ₹30,000, which falls comfortably within the ₹50,000 Shishu ceiling.',
        userValue: '₹30,000 required',
        requiredRule: 'Maximum ₹50,000 for Shishu tier',
      },
      {
        id: 'crit_4',
        label: 'No prior bank default status',
        status: 'unknown',
        explanation: 'Bank credit verification required during bank branch document verification.',
        userValue: 'Unverified with credit bureau',
        requiredRule: 'Applicant must not be in default with any financial institution',
      },
    ],
  },
  {
    id: 'sch_standup_india',
    officialName: 'Stand-Up India Scheme for Women and SC/ST Entrepreneurs',
    popularName: 'Stand-Up India Enterprise Loan',
    schemeType: 'loan',
    implementingAuthority: 'Department of Financial Services (DFS), Govt. of India',
    description: 'Facilitates bank loans between ₹10 Lakhs and ₹1 Crore to at least one woman borrower per bank branch for setting up a greenfield enterprise in manufacturing, services, or trading sector.',
    targetBeneficiaries: ['Women entrepreneurs starting new greenfield ventures above ₹10 Lakhs'],
    eligibleSectors: ['food_snacks', 'tailoring_clothing', 'beauty_wellness', 'agriculture_farming', 'retail_shop', 'digital_services'],
    geographicScope: 'Pan India (Scheduled Commercial Banks)',
    maxFundingAmountINR: 10000000,
    interestRateAnnualPercent: 9.25,
    collateralRequired: true,
    applicationUrl: 'https://www.standupmitra.in',
    officialSourceUrl: 'https://www.standupmitra.in',
    lastVerifiedDate: '2026-01-20',
    recordStatus: 'active',
    sourceExcerpt: 'The scheme covers greenfield projects only. Loans range between ₹10 Lakh to ₹100 Lakh. Margin money can be backed by eligible subsidy schemes.',
    whyRecommended: 'Recognized national woman entrepreneur scheme, but current planned budget (₹30,000) is far below the mandatory minimum threshold of ₹10 Lakhs.',
    overallStatus: 'ineligible',
    requiredDocuments: ['Aadhaar Card', 'Detailed Project Report (DPR)', 'Proof of non-farm manufacturing/service', 'Bank statement', 'PAN Card', 'Udyam Registration'],
    criteria: [
      {
        id: 'crit_su_1',
        label: 'Woman borrower or SC/ST entrepreneur',
        status: 'pass',
        explanation: 'Applicant is a woman entrepreneur eligible for Stand-Up India allocation.',
        userValue: 'Woman Entrepreneur',
        requiredRule: 'Woman or SC/ST individual',
      },
      {
        id: 'crit_su_2',
        label: 'Minimum project outlay ₹10,00,000',
        status: 'fail',
        explanation: 'Your current business budget is ₹30,000. Stand-Up India specifically targets enterprises requiring ₹10 Lakhs or more.',
        userValue: '₹30,000 budget',
        requiredRule: 'Loan ticket between ₹10 Lakh and ₹100 Lakh',
      },
      {
        id: 'crit_su_3',
        label: 'Greenfield venture (first-time business in this sector)',
        status: 'pass',
        explanation: 'This is your first enterprise initiative.',
        userValue: 'New venture',
        requiredRule: 'Must be first-time greenfield enterprise',
      },
    ],
  },
  {
    id: 'sch_annapurna_food',
    officialName: 'Annapurna Scheme for Women Food Catering Units',
    popularName: 'Annapurna Food & Catering Assistance',
    schemeType: 'loan',
    implementingAuthority: 'Public Sector Banks in partnership with State Social Welfare Boards',
    description: 'Provides micro-loans up to ₹50,000 for women establishing packaged lunch, snack catering, or food stalls to buy kitchen equipment, gas connection, water filters, and cookware.',
    targetBeneficiaries: ['Women setting up food preparation units, tiffin services, and street breakfast stalls'],
    eligibleSectors: ['food_snacks'],
    geographicScope: 'Pan India (Designated Nationalized and Rural Banks)',
    maxFundingAmountINR: 50000,
    interestRateAnnualPercent: 8.75,
    collateralRequired: false,
    applicationUrl: 'https://www.myscheme.gov.in',
    officialSourceUrl: 'https://www.myscheme.gov.in',
    lastVerifiedDate: '2026-02-15',
    recordStatus: 'active',
    sourceExcerpt: 'Women catering units can avail up to ₹50,000 to purchase kitchen equipment. A guarantor is required by participating banks with flexible repayment over 36 months.',
    whyRecommended: 'Specifically crafted for women starting food and snack stalls. Matches your exact sector (tea & snacks) and available investment tier.',
    overallStatus: 'potentially_eligible',
    requiredDocuments: ['Identity Proof (Aadhaar)', 'Residence Certificate', 'Kitchen equipment vendor estimate', 'Bank Account details', 'Third-party guarantor consent form'],
    criteria: [
      {
        id: 'crit_an_1',
        label: 'Food and catering trade activity',
        status: 'pass',
        explanation: 'Your planned venture is a tea and morning snack stall.',
        userValue: 'Tea & Snacks',
        requiredRule: 'Food preparation or catering',
      },
      {
        id: 'crit_an_2',
        label: 'Requires one third-party guarantor',
        status: 'unknown',
        explanation: 'Need to confirm whether an acceptable guarantor (family member or SHG leader) is available.',
        userValue: 'Not yet recorded',
        requiredRule: 'Must provide bank-accepted guarantor',
      },
    ],
  },
  {
    id: 'sch_pmegp_subsidy',
    officialName: 'Prime Minister’s Employment Generation Programme (PMEGP)',
    popularName: 'PMEGP Subsidy Scheme (Up to 35% Govt. Subsidy)',
    schemeType: 'subsidy',
    implementingAuthority: 'Khadi and Village Industries Commission (KVIC) / MSME Ministry',
    description: 'Credit-linked subsidy programme to generate self-employment in rural and semi-urban areas. Special category women in rural areas receive 35% margin money subsidy on project cost.',
    targetBeneficiaries: ['Rural women entrepreneurs', 'SHG members', 'First-time village business owners'],
    eligibleSectors: ['food_snacks', 'tailoring_clothing', 'beauty_wellness', 'handmade_crafts', 'retail_shop'],
    geographicScope: 'Rural and Urban India (Higher 35% subsidy rate in rural locations)',
    maxFundingAmountINR: 2000000,
    interestRateAnnualPercent: 9.0,
    subsidyPercentage: 35,
    collateralRequired: false,
    applicationUrl: 'https://www.kviconline.gov.in/pmegp',
    officialSourceUrl: 'https://www.kviconline.gov.in',
    lastVerifiedDate: '2026-03-01',
    recordStatus: 'active',
    sourceExcerpt: 'For rural women beneficiaries, the government subsidy (margin money) is 35% of the project cost, with only 5% beneficiary own contribution required.',
    whyRecommended: 'As a woman operating in rural Shirur (Pune rural), you are entitled to the highest 35% government subsidy if your equipment investment is formalised.',
    overallStatus: 'eligible',
    requiredDocuments: ['Aadhaar Card', 'Rural Area Certificate from Gram Panchayat', 'Project Report / Cost Estimate', 'Educational Certificate', 'Bank Account Details'],
    criteria: [
      {
        id: 'crit_pm_1',
        label: 'Age above 18 years',
        status: 'pass',
        explanation: 'Age criterion fully met.',
        userValue: 'Age 26-35',
        requiredRule: 'Minimum 18 years old',
      },
      {
        id: 'crit_pm_2',
        label: 'Rural classification verification',
        status: 'pass',
        explanation: 'Shirur rural classification entitles you to 35% subsidy rate instead of 25% urban rate.',
        userValue: 'Rural Pune',
        requiredRule: 'Rural area as certified by local authority',
      },
      {
        id: 'crit_pm_3',
        label: 'Beneficiary contribution capacity (5%)',
        status: 'pass',
        explanation: '5% of a ₹30,000 to ₹50,000 project is ₹1,500 to ₹2,500, which is well within your ₹30,000 savings.',
        userValue: '₹30,000 savings',
        requiredRule: '5% own contribution for special category',
      },
    ],
  },
];

export const INITIAL_DEMO_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc_aadhaar',
    name: 'Aadhaar Card with Linked Mobile Number',
    purpose: 'Primary identity verification and digital e-KYC for banking & scheme applications',
    isMandatory: true,
    requirementType: 'mandatory',
    status: 'available',
    howToObtain: 'Available with you. Ensure the active mobile SIM is linked to receive OTPs during bank verification.',
    issuingAuthority: 'Unique Identification Authority of India (UIDAI)',
    officialReferenceUrl: 'https://myaadhaar.uidai.gov.in',
    sourceSchemeId: 'sch_mudra_shishu',
    verifiedSourceDate: '2026-02-10',
  },
  {
    id: 'doc_bank_passbook',
    name: 'Savings Bank Passbook (Last 6 Months)',
    purpose: 'Proof of active bank account and financial transactions for loan disbursement',
    isMandatory: true,
    requirementType: 'mandatory',
    status: 'available',
    howToObtain: 'Visit your Bank of Maharashtra or local Gramin Bank branch in Shirur to update entries for the last 6 months.',
    issuingAuthority: 'Bank of Maharashtra / Local Branch',
    sourceSchemeId: 'sch_mudra_shishu',
    verifiedSourceDate: '2026-02-10',
  },
  {
    id: 'doc_pan',
    name: 'PAN Card or Form 60',
    purpose: 'Tax identification and mandatory banking requirement for commercial loan accounts',
    isMandatory: true,
    requirementType: 'conditional',
    conditionNote: 'Form 60 declaration accepted if PAN is pending for loans below ₹50,000',
    status: 'needed',
    howToObtain: 'Apply online through Protean/UTIITSL or submit Form 60 at the bank branch if PAN is pending.',
    issuingAuthority: 'Income Tax Department of India',
    officialReferenceUrl: 'https://www.onlineservices.nsdl.com',
    sourceSchemeId: 'sch_mudra_shishu',
    verifiedSourceDate: '2026-02-10',
  },
  {
    id: 'doc_equipment_quotation',
    name: 'Vendor Quotation for Cooking Utensils & Burner',
    purpose: 'Bank requires written price estimate to disburse Mudra loan directly or against capital expenditure',
    isMandatory: true,
    requirementType: 'conditional',
    conditionNote: 'Required when financing equipment purchase rather than general working capital',
    status: 'needed',
    howToObtain: 'Ask a local stainless steel / kitchen utensils shopkeeper in Shirur market for a written quotation bill for the burner, kettle, and dishes (~₹14,000).',
    issuingAuthority: 'Registered Local Merchant / Shopkeeper',
    sourceSchemeId: 'sch_mudra_shishu',
    verifiedSourceDate: '2026-02-10',
  },
  {
    id: 'doc_fssai_reg',
    name: 'FSSAI Food Safety Basic Registration (Form A)',
    purpose: 'Legal license required for any food preparation and snack vending in India (Turnover under ₹12 Lakhs)',
    isMandatory: true,
    requirementType: 'mandatory',
    status: 'needed',
    howToObtain: 'Apply online at FoSCoS portal with Aadhaar and photo. Government fee is ₹100/year for petty food businesses.',
    issuingAuthority: 'Food Safety and Standards Authority of India (FSSAI)',
    officialReferenceUrl: 'https://foscos.fssai.gov.in',
    sourceSchemeId: 'sch_annapurna_food',
    verifiedSourceDate: '2026-02-15',
  },
  {
    id: 'doc_gram_noc',
    name: 'Gram Panchayat / Nagar Parishad Stall NOC or Vending Receipt',
    purpose: 'Permission to set up stall along market road without clearance disputes',
    isMandatory: false,
    requirementType: 'optional',
    conditionNote: 'Recommended for street stall vendors to prevent eviction disputes',
    status: 'needed',
    howToObtain: 'Meet the Shirur local authority / Gram Sevak to register as a local street vendor under PM SVANidhi / local vendor register.',
    issuingAuthority: 'Shirur Gram Panchayat / Town Vending Committee',
    sourceSchemeId: 'sch_pm_svanidhi',
    verifiedSourceDate: '2026-01-18',
  },
  {
    id: 'doc_udyam',
    name: 'Udyam Registration Certificate (Micro Enterprise)',
    purpose: 'Official MSME certificate giving access to priority sector lending and government subsidies',
    isMandatory: false,
    requirementType: 'optional',
    conditionNote: 'Free government registration; optional for loans < ₹50k but expedited processing',
    status: 'needed',
    howToObtain: 'Free self-declaration registration online using Aadhaar and mobile OTP at official portal.',
    issuingAuthority: 'Ministry of Micro, Small and Medium Enterprises',
    officialReferenceUrl: 'https://udyamregistration.gov.in',
    sourceSchemeId: 'sch_mudra_shishu',
    verifiedSourceDate: '2026-02-10',
  },
];

export const INITIAL_DEMO_ACTION_PLAN: ActionPlanTask[] = [
  // Days 1-7
  {
    id: 'task_01',
    phase: 'days_1_7',
    title: 'Market Footfall & Taste Test Survey',
    description: 'Visit the Shirur bus station and market junction between 7:30 AM – 9:30 AM. Observe how many people buy morning tea and poha, and note their prices (typically ₹10 tea, ₹20 poha).',
    estimatedDays: 3,
    estimatedCostINR: 200,
    materialsNeeded: ['Notepad', 'Pen', 'Sample poha to offer 5 family neighbors for feedback'],
    dependencies: [],
    scheduledDate: 'Day 1–3',
    completionState: 'completed',
    isCompleted: true,
    status: 'completed',
    relatedRecommendationOrSource: 'Field customer demand validation before spending capital',
  },
  {
    id: 'task_02',
    phase: 'days_1_7',
    title: 'Lock Stall Location & Landowner / Panchayat Permission',
    description: 'Find a safe, clean 6x4 feet dry spot with customer shade. Confirm with the shopfront owner or Gram Panchayat that morning stall placement is permitted.',
    estimatedDays: 4,
    estimatedCostINR: 0,
    materialsNeeded: ['Aadhaar copy', 'Written consent note'],
    dependencies: ['task_01'],
    scheduledDate: 'Day 4–7',
    completionState: 'completed',
    isCompleted: true,
    status: 'completed',
    relatedRecommendationOrSource: 'Local vending regulations and Gram Panchayat permission',
  },

  // Days 8-14
  {
    id: 'task_03',
    phase: 'days_8_14',
    title: 'Collect Itemized Equipment Quotations',
    description: 'Get written estimates from 2 utensil shops in Shirur for 1 commercial gas stove, regulator, 10L tea kettle, 3 stainless steel trays, and 50 reusable washable cups or paper cups.',
    estimatedDays: 3,
    estimatedCostINR: 0,
    materialsNeeded: ['Shop visit', 'Price comparison sheet'],
    dependencies: ['task_02'],
    scheduledDate: 'Day 8–10',
    completionState: 'in_progress',
    isCompleted: false,
    status: 'in_progress',
    relatedSchemeId: 'sch_mudra_shishu',
    relatedRecommendationOrSource: 'Mandatory documentation for Mudra Shishu capital expenditure',
  },
  {
    id: 'task_04',
    phase: 'days_8_14',
    title: 'Calculate 7-Day Ingredient Working Capital',
    description: 'List initial ingredients: 5kg tea leaves, 15kg sugar, 20L milk estimate, 10kg poha, spices, and cooking oil. Total 7-day reserve needed: ~₹4,500.',
    estimatedDays: 2,
    estimatedCostINR: 4500,
    materialsNeeded: ['Wholesale grain vendor contacts'],
    dependencies: ['task_03'],
    scheduledDate: 'Day 11–14',
    completionState: 'pending',
    isCompleted: false,
    status: 'pending',
    relatedRecommendationOrSource: 'Working capital cushion for cash flow stability',
  },

  // Days 15-21
  {
    id: 'task_05',
    phase: 'days_15_21',
    title: 'Apply for Mudra Shishu Loan at Local Bank Branch',
    description: 'Submit Mudra Shishu 1-page form along with Aadhaar, passbook copy, and the equipment quotation to Bank of Maharashtra Shirur branch for ₹20,000 - ₹30,000 support.',
    estimatedDays: 5,
    estimatedCostINR: 100,
    materialsNeeded: ['Aadhaar', 'Bank passbook', 'Vendor quotation', '2 Photos'],
    dependencies: ['task_03', 'task_04'],
    scheduledDate: 'Day 15–19',
    completionState: 'pending',
    isCompleted: false,
    relatedSchemeId: 'sch_mudra_shishu',
    status: 'pending',
    relatedRecommendationOrSource: 'Official portal: https://www.mudra.org.in',
  },
  {
    id: 'task_06',
    phase: 'days_15_21',
    title: 'FSSAI Basic Food Registration Application',
    description: 'Apply for FSSAI registration certificate on FoSCoS portal (₹100 annual fee) to operate legally and build customer hygiene trust.',
    estimatedDays: 2,
    estimatedCostINR: 100,
    materialsNeeded: ['Aadhaar card copy', 'Passport size photo', 'Mobile for OTP'],
    dependencies: ['task_02'],
    scheduledDate: 'Day 20–21',
    completionState: 'pending',
    isCompleted: false,
    status: 'pending',
    relatedRecommendationOrSource: 'Official portal: https://foscos.fssai.gov.in',
  },

  // Days 22-30
  {
    id: 'task_07',
    phase: 'days_22_30',
    title: 'Trial Run with Neighbors & Family (Soft Launch)',
    description: 'Prepare test batches of spiced masala tea and hot poha at home. Practice boiling speed, spice measurements, packaging, and clean water handling.',
    estimatedDays: 2,
    estimatedCostINR: 600,
    materialsNeeded: ['Ingredients', 'Cleaning napkins', 'Drinking water can'],
    dependencies: ['task_04'],
    scheduledDate: 'Day 22–24',
    completionState: 'pending',
    isCompleted: false,
    status: 'pending',
    relatedRecommendationOrSource: 'Product taste consistency and customer feedback check',
  },
  {
    id: 'task_08',
    phase: 'days_22_30',
    title: 'Stall Opening Day & QR Code Payment Setup',
    description: 'Set up stall with clean banner, offer free taste cups to first 20 passers-by, display PhonePe / GPay QR code for easy UPI payments, and record day 1 cash balance.',
    estimatedDays: 1,
    estimatedCostINR: 500,
    materialsNeeded: ['Laminated name board', 'Bank UPI QR standee', 'Change cash reserve ₹500'],
    dependencies: ['task_05', 'task_07'],
    scheduledDate: 'Day 25–30',
    completionState: 'pending',
    isCompleted: false,
    status: 'pending',
    relatedRecommendationOrSource: 'Digital payments and soft opening promotion',
  },
];
